# -*- coding: utf-8 -*-
"""Shelter_cats_eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jJYTrGZQO3tXbSk7x_3luWK1T05FlGLc

# Shelter Cats Exploratory Data Analysis

# 1.&nbsp; Introduction

This dataset comes from the Austin Animal Center, or ACC, based in Austin, Texas. The ACC is the biggest no-kill animal shelter in the United States, sheltering over ___ animals on average every year. The data collected dates back to October 1st, 2013 and is updated frequently. I recently adopted my first pet from a shelter, an adult cat, after being told by many others that older cats oftentimes spend more time in shelters than their younger counterparts. This exploratory data analysis serves as a tool to investigate whether or not the age of a cat affects its chances of adoption and to search for any other possible factors affecing their adoptability. Learning more about what kinds of cats are not being adopted can help educate the general public and increase the overall adoptability of cats.

The dataset can be found [here](https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Outcomes/9t4d-g238).

# 2.&nbsp; Data Preparation and Cleaning
"""

import pandas as pd
import numpy as np

a_out = pd.read_csv('/content/Austin_Animal_Center_Outcomes_20231018.csv', on_bad_lines='skip')

a_in = pd.read_csv('/content/Austin_Animal_Center_Intakes_20231018.csv', on_bad_lines='skip')

data = pd.merge(
    a_in,
    a_out,
    on = ['Animal ID', 'Name', 'Animal Type', 'Breed', 'Color']
)

data.head()

data.shape

data.rename(columns = {
        'DateTime_x': 'Intake DateTime', 'MonthYear_x': 'Intake MonthYear',
        'DateTime_y': 'Outcome DateTime', 'MonthYear_y': 'Outcome MonthYear'
    }, inplace = True)

data.head()

data['Intake DateTime'][0]

data[['Intake DateTime', 'Outcome DateTime']] = data[['Intake DateTime', 'Outcome DateTime']].apply(pd.to_datetime)

data['Total Days in Shelter'] = (data['Outcome DateTime'] - data['Intake DateTime']) / pd.Timedelta(days=1)

data.head()

# Now that our data is organized, subset cats

cats = data[data['Animal Type'] == 'Cat']

cats.head()

cats.describe()

# in comparison to dogs?
dogs = data[data['Animal Type'] == 'Dog']
dogs.describe()

data.shape

cats.shape

cats['Outcome Type'].unique()

cat_adopt = cats[(cats['Outcome Type'] == 'Rto-Adopt') | (cats['Outcome Type'] == 'Adoption') | (cats['Outcome Type'] == 'Return to Owner')]
cat_adopt.head()

cat_adopt.describe()

cat_adopt.isnull().mean()

cat_adopt['Outcome Subtype'].unique()

"""Although a large proportion of data for the outcome subtype variable is missing, I will choose to not remove it at this point since for the cats that do have that information, there is possibly information that can be found.

# 3.&nbsp; Exploratory Analysis and Visualizations
"""

import altair as alt
alt.data_transformers.disable_max_rows()

cat_adopt['Age upon Outcome'].unique()

ages = ['1 weeks', '2 weeks', '3 weeks', '4 weeks', '1 month', '2 months',
        '3 months', '4 months', '5 months', '6 months', '7 months', '8 months',
        '9 months', '10 months', '11 months', '0 years', '1 year', '2 years',
        '3 years', '4 years', '5 years', '6 years', '7 years', '8 years',
        '9 years', '10 years', '11 years', '12 years', '13 years', '14 years',
        '15 years', '16 years', '17 years', '18 years', '19 years', '20 years',
        '21 years', '22 years']

# x = alt.X('Age upon Outcome',
        #      sort=alt.EncodingSortField(field="Age upon Outcome",
        #                                 op="count", order='descending'))

alt.Chart(cat_adopt).mark_bar().encode(
    x = alt.X('Age upon Outcome',
              sort = ages),
    y = alt.Y('count()'),
    color = alt.Color('Total Days in Shelter')
)

alt.Chart(cat_adopt).mark_bar().encode(
    x = alt.X('Age upon Outcome',
              sort = ages),
    y = alt.Y('mean(Total Days in Shelter)')
)

# how is 1 week such a negative value? 0 years as well

cat_adopt[(cat_adopt['Age upon Outcome'] == '1 weeks') | (cat_adopt['Age upon Outcome'] == '0 years')]

# clearly there has been an error either in my data processing or in the data entry

cats[(cats['Age upon Outcome'] == '1 weeks') & (cats['Total Days in Shelter'] < 0)]

# did i merge the data incorrectly? did i create the days in shelter variable incorrectly?
# i can also just change the negative values to positive since they are the same
# magnitude as if the days were correctly stored

# next make the correlation heatmap

corr_mx = cat_adopt.corr()

# melt corr_mx
corr_mx_long = corr_mx.reset_index().rename(
    columns = {'index': 'row'}
).melt(
    id_vars = 'row',
    var_name = 'col',
    value_name = 'Correlation'
)

# construct plot
alt.Chart(corr_mx_long).mark_rect().encode(
    x = alt.X('col', title = '', sort = {'field': 'Correlation', 'order': 'ascending'}),
    y = alt.Y('row', title = '', sort = {'field': 'Correlation', 'order': 'ascending'}),
    color = alt.Color('Correlation',
                      scale = alt.Scale(scheme = 'blueorange', # diverging gradient
                                        domain = (-1, 1), # ensure white = 0
                                        type = 'sqrt'), # adjust gradient scale
                     legend = alt.Legend(tickCount = 5)) # add ticks to colorbar at 0.5 for reference
).properties(width = 300, height = 300)









"""# 4.&nbsp; Ask and Answer Questions"""







"""# 5.&nbsp; Summary and Conclusion"""





